# Config version
[global]
# The version of this configuration file.
version = 1
# Specifies the active space: "core", "eSpace", or "all".
space = "all"
# The output directory for generated files.
workdir = "./frontend"

[proxy]
# Set to true to enable proxy configuration generation.
enabled = true
# Specifies the proxy type, e.g., "nginx".
type = "nginx"

# Proxy configuration for Core Space.
[proxy.core_space]
# The backend API URL for Core Space.
api_url = "https://testnet.confluxscan.io"
# Port for the Core Space proxy.
port = 3000

# Proxy configuration for eSpace.
[proxy.e_space]
# The backend API URL for eSpace.
api_url = "https://evmtestnet.confluxscan.org"
port = 3001

# Settings for running the frontend in a container.
[container]
# Set to true to enable container configuration.
enabled = true
# Specifies the container type: "docker", or "docker-compose".
type = "docker-compose" # Example: "docker-compose"
name = "scan-frontend"
tag = "latest"

[container.core_space]
# Port mapping for the Core Space container.
port = 8000

[container.e_space]
# Port mapping for the eSpace container.
port = 8001

# Frontend settings
[frontend]
# Specifies the frontend type: "prebuilt" or "source".
type = "prebuilt"
# sirius_repo = "https://github.com/Conflux-Chain/sirius.git"
# sirius_eth_repo = "https://github.com/Conflux-Chain/sirius-eth.git"
prebuilt_repo = "https://github.com/Conflux-Chain/sirius-auto-release.git"

# Custom frontend settings for Core Space
[frontend.core_space_settings]
enabled = true

ENV_OPEN_API_HOST = "https://api-testnet.confluxscan.net"
ENV_RPC_SERVER = "https://test.confluxrpc.com"
ENV_NETWORK_ID = 1
ENV_NETWORK_TYPE = "CORE"
ENV_CHAIN_TYPE = "TESTNET"
ENV_FC_ADDRESS = "cfxtest:achteu1f777f1j1s8s4tvsx5vk5vcbrn4ykxa0fzg1"
ENV_FC_EXCHANGE_ADDRESS = "cfxtest:acf6wwargxpp9ddfe7rnagf2ty9gsxs54uptst589y"
ENV_FC_EXCHANGE_INTEREST_ADDRESS = "cfxtest:acadrvdd07u69hazg0nkjkpdetvyc5wma6put8949d"
ENV_ENS_REGISTRY_ADDRESS = "cfxtest:acemru7fu1u8brtyn3hrtae17kbcd4pd9u2m761bta"
ENV_ENS_PUBLIC_RESOLVER_ADDRESS = "cfxtest:acbfyf69zaxau5a23w10dgyrmb0hrz4p9pewn6sejp"
ENV_LOGO = "https://testnet.confluxscan.net/static/media/logo-testnet.135b93ff.svg"

# Custom frontend settings for eSpace
[frontend.e_space_settings]
enabled = true

ENV_API_HOST = "https://evmapi-testnet.confluxscan.net"
ENV_CORE_API_HOST = "https://api-testnet.confluxscan.net"
ENV_CORE_SCAN_HOST = "https://testnet.confluxscan.net"
ENV_RPC_SERVER = "https://evmtestnet-cfxbridge.confluxrpc.com"
ENV_NETWORK_ID = 71
ENV_NETWORK_TYPE = "EVM"
ENV_CHAIN_TYPE = "TESTNET"
ENV_LOGO = "https://evmtestnet.confluxscan.net/static/media/logo-testnet.6a5c7ce7.svg"

[frontend.e_space_settings.ENV_WALLET_CONFIG]
chainId = 71
chainName = "eSpace Testnet"
rpcUrls = ["https://evmtestnet.confluxrpc.com"]
blockExplorerUrls = ["https://evmtestnet.confluxscan.org"]
[frontend.e_space_settings.ENV_WALLET_CONFIG.nativeCurrency]
name = "Conflux"
symbol = "CFX"
decimals = 18

[frontend.e_space_settings.ENV_THEME]
primary = "#17B38A"
antdPrimaryButtonBg = "#7789D3"
buttonBg = "rgba(0, 84, 254, 0.8)"
outlineColor = "#7789D3"
shadowColor = "rgba(30, 61, 228, 0.2)"
searchButtonBg = "#AFE9D2"
searchButtonHoverBg = "#17B38A"
gasPriceLineBg = "#F0F4F3"
footerBg = "#05343F"
footerHighLightColor = "#AFE9D2"
linkColor = "#1e3de4"
linkHoverColor = "#0f23bd"
chartColors = [
    "#7cb5ec",
    "#434348",
    "#f7a35c",
    "#2b908f",
    "#91e8e1",
    "#90ed7d",
    "#8085e9",
    "#f15c80",
    "#e4d354",
    "#f45b5b",
]
mixedChartColors = ["#7cb5ec", "#90ed7d", "#434348"]
pieChartColors = [
    "#7cb5ec",
    "#434348",
    "#f7a35c",
    "#2b908f",
    "#91e8e1",
    "#90ed7d",
    "#8085e9",
    "#f15c80",
    "#e4d354",
    "#f45b5b",
]
chartTitleColor = "#7789D3"
chartDetailLinkColor = "#1e3de4"

[frontend.e_space_settings.ENV_ICONS]
imgArrow = "/static/media/arrow.4e79d439.svg"


[frontend.e_space_settings.ENV_LOCALES_EN]


[frontend.e_space_settings.ENV_LOCALES_CN]
