# Config version
[global]
# The version of this configuration file.
version = 1

# Specifies the active space for the frontend: "core", "eSpace", or "all".
# "core": Only Core Space frontend will be configured and/or built.
# "eSpace": Only eSpace frontend will be configured and/or built.
# "all": Both Core Space and eSpace frontends will be configured and/or built.
space = "all"

# The output directory for generated files and frontend build artifacts.
workdir = "./frontend"


# Frontend settings
[frontend]
# Specifies the frontend type.
#   "prebuilt": Uses pre-downloaded frontend files from `prebuilt_repo`.
type = "prebuilt"

prebuilt_repo = "https://github.com/Conflux-Chain/sirius-auto-release.git"

[frontend.core_space_settings]
# Backend service URL for Core Space.
# The frontend application will make requests (e.g., to /v1, /stat) to this URL.
# If containerization with Nginx proxy is enabled (see [container] and [proxy] sections),
# this URL is typically the upstream target for the Nginx proxy.
api_url = "https://testnet.confluxscan.io"

[frontend.e_space_settings]
# Backend service URL for eSpace.
# The frontend application will make requests (e.g., to /v1, /stat) to this URL.
# If containerization with Nginx proxy is enabled (see [container] and [proxy] sections),
# this URL is typically the upstream target for the Nginx proxy.
api_url = "https://evmtestnet.confluxscan.org"


# Settings for running the frontend in a container (Docker/Docker Compose).
[container]
# Set to true to enable containerization. If true, a Dockerfile (and optionally
# docker-compose.yml) will be generated, and Nginx will be used internally for serving.
enabled = true
# Specifies the container tooling:
#   "docker": Generates only a Dockerfile.
#   "docker-compose": Generates a Dockerfile and a docker-compose.yml file.
# type = "docker"
type = "docker-compose"
# Name for the Docker container or service (if using Docker Compose).
name = "scan-frontend"
# Tag for the Docker image (e.g., "latest", "v1.0.0").
tag = "latest"

[container.core_space]
# Host port mapping for the Core Space service container.
# This is the port on your host machine that maps to the container's internal
# Nginx service port (defined in `proxy.core_space.port`).
port = 8000

[container.e_space]
# Host port mapping for the eSpace service container.
# This is the port on your host machine that maps to the container's internal
# Nginx service port (defined in `proxy.e_space.port`).
port = 8001


# Proxy settings, primarily used when `container.enabled = true`.
# Nginx within the container(s) will use these settings to proxy frontend API requests.
[proxy]

# Proxy configuration for Core Space (when container.enabled = true).
[proxy.core_space]
# Target backend API URL for the Core Space Nginx proxy.
# Requests received by the Nginx service (listening internally on `proxy.core_space.port`)
# will be forwarded to this `api_url`. This often matches `frontend.core_space_settings.api_url`.
api_url = "https://testnet.confluxscan.io"
# Internal port inside the container where the Nginx service for Core Space will listen.
# Ensure this port does not conflict with `proxy.e_space.port` if both are used.
port = 3000

# Proxy configuration for eSpace (when container.enabled = true).
[proxy.e_space]
# Internal port inside the container where the Nginx service for eSpace will listen.
# Ensure this port does not conflict with `proxy.core_space.port` if both are used.
# Note: `api_url` is not specified here for eSpace proxy. The Nginx configuration
# for eSpace will likely use `frontend.e_space_settings.api_url` as its upstream target.
port = 3001
